const language_data = [
  { key_name: 'login_page', en: 'Log in', sv: 'Logga in' },
  { key_name: 'email_placeholder', en: 'Email address', sv: 'E-postadress' },
  { key_name: 'password_placeholder', en: 'Password', sv: 'Lösenord' },
  { key_name: 'login_button', en: 'Log in', sv: 'Logga in' },
  { key_name: 'register_link', en: 'Register', sv: 'Registrera' },
  { key_name: 'forgotten_password_link', en: 'Forgotten password?', sv: 'Glömt lösenord?' },
  { key_name: 'menu_home', en: 'Home', sv: 'Hem' },
  { key_name: 'menu_order', en: 'Order', sv: 'Beställning' },
  { key_name: 'menu_our_customers', en: 'Our Customers', sv: 'Våra kunder' },
  { key_name: 'menu_about_us', en: 'About us', sv: 'Om oss' },
  { key_name: 'menu_contact_us', en: 'Contact Us', sv: 'Kontakta oss' },
  { key_name: 'language_label', en: 'English', sv: 'Svenska' },
  { key_name: 'footer_company_name', en: '123 Fakturera', sv: '123 Fakturera' },
  { key_name: 'footer_rights', en: 'All rights reserved.', sv: 'Alla rättigheter förbehållna.' },
  { key_name: 'app_title', en: 'John Andre', sv: 'John Andre' },
  { key_name: 'company_name', en: 'Storjord AS', sv: 'Storjord AS' },
  { key_name: 'menu_invoices', en: 'Invoices', sv: 'Fakturor' },
  { key_name: 'menu_customers', en: 'Customers', sv: 'Kunder' },
  { key_name: 'menu_my_business', en: 'My Business', sv: 'Mitt företag' },
  { key_name: 'menu_invoice_journal', en: 'Invoice journal', sv: 'Fakturajournal' },
  { key_name: 'menu_price_list', en: 'Price List', sv: 'Prislista' },
  { key_name: 'menu_multiple_invoicing', en: 'Multiple Invoicing', sv: 'Flera faktureringar' },
  { key_name: 'menu_unpaid_invoices', en: 'Unpaid Invoices', sv: 'Obetalda fakturor' },
  { key_name: 'menu_offer', en: 'Offer', sv: 'Erbjudande' },
  { key_name: 'menu_inventory_control', en: 'Inventory Control', sv: 'Lagerkontroll' },
  { key_name: 'menu_member_invoicing', en: 'Member Invoicing', sv: 'Medlemsfakturering' },
  { key_name: 'menu_import_export', en: 'Import/Export', sv: 'Importera/Exportera' },
  { key_name: 'menu_log_out', en: 'Log out', sv: 'Logga ut' },
  { key_name: 'search_article_no', en: 'Search Article No...', sv: 'Sök artikelnummer...' },
  { key_name: 'search_product', en: 'Search Product...', sv: 'Sök produkt...' },
  { key_name: 'button_new_product', en: 'New Product', sv: 'Ny produkt' },
  { key_name: 'button_print_list', en: 'Print List', sv: 'Skriv ut lista' },
  { key_name: 'button_advanced_mode', en: 'Advanced mode', sv: 'Avancerat läge' },
  { key_name: 'table_header_article_no', en: 'Article No.', sv: 'Artikelnummer.' },
  { key_name: 'table_header_product_service', en: 'Product/Service', sv: 'Produkt/Tjänst' },
  { key_name: 'table_header_in_price', en: 'In Price', sv: 'Inköpspris' },
  { key_name: 'table_header_price', en: 'Price', sv: 'Pris' },
  { key_name: 'table_header_unit', en: 'Unit', sv: 'Enhet' },
  { key_name: 'table_header_in_stock', en: 'In Stock', sv: 'I lager' },
  { key_name: 'table_header_description', en: 'Description', sv: 'Beskrivning' },
  { key_name: 'invoice_now_button', en: 'Invoice Now', sv: 'Fakturera Nu' },
  { key_name: 'terms_intro', en: 'By clicking Invoice Now, you choose to register according to the information that you have typed in and the text on the registration page and the terms here, and you at the same time accept the terms here.', sv: 'BY clicking Invoice Now, you choose to register according to the information that you have typed in and the text on the registration page and the terms here, and you at the same time accept the terms here.' },
  { key_name: 'free_trial_period', en: 'You can use the program FOR FREE for 14 days.', sv: 'You can use the program FOR FREE for 14 days.' },
  { key_name: 'support_info', en: '123 Fakturera is so easy and self-explanatory that the chance that you will need support is minimal, but if you should need support, we are here for you, with our office manned for the most part of the day.', sv: '123 Fakturera is so easy and self-explanatory that the chance that you will need support is minimal, but if you should need support, we are here for you, with our office manned for the most part of the day.' },
  { key_name: 'subscription_price', en: 'After the trial period, the subscription continues and costs SEK 99 excluding VAT per month, which is billed annually.', sv: 'After the trial period, the subscription continues and costs SEK 99 excluding VAT per month, which is billed annually.' },
  { key_name: 'cancel_trial_how', en: 'If you do not want to keep the program, just cancel the trial period by giving notice before 14 days from registration.', sv: 'If you do not want to keep the program, just cancel the trial period by giving notice before 14 days from registration.' },
  { key_name: 'cancel_free', en: 'You have of course the right to terminate the use of the program without any costs, by giving us notice per email before 14 days from registration, that you do not want to continue with the program, and you then of course do not pay anything.', sv: 'You have of course the right to terminate the use of the program without any costs, by giving us notice per email before 14 days from registration, that you do not want to continue with the program, and you then of course do not pay anything.' },
  { key_name: 'no_cancellation_after_14', en: 'If we do not receive such a notice from you before 14 days from registration, then the order, for natural reasons, cannot be changed.', sv: 'If we do not receive such a notice from you before 14 days from registration, then the order, for natural reasons, cannot be changed.' },
  { key_name: 'registration_definition', en: 'With registration it is meant the date and time when you did choose to press the button Invoice Now.', sv: 'With registration it is meant the date and time when you did choose to press the button Invoice Now.' },
  { key_name: 'billing_cycle', en: 'Billing is for one year at a time.', sv: 'Billing is for one year at a time.' },
  { key_name: 'price_details', en: 'The price for 123 Fakturera (offer price SEK 99 per month / ordinary price SEK 159 per month) is for the annual fee Start for one year\'s use of the program.', sv: 'The price for 123 Fakturera (offer price SEK 99 per month / ordinary price SEK 159 per month) is for the annual fee Start for one year\'s use of the program.' },
  { key_name: 'offer_period_calc', en: 'When using the offer price of SEK 99, the one-year period is calculated from registration.', sv: '(When using the offer price of SEK 99, the one-year period is calculated from registration.)' },
  { key_name: 'vat_note', en: 'All prices are excluding VAT.', sv: 'All prices are excluding. VAT.' },
  { key_name: 'additional_modules', en: 'Offer, Inventory Control, Member Invoicing, Multiuser version and English printout are (or can be) additional modules that can be ordered later.', sv: 'Offer, Inventory Control, Member Invoicing, Multiuser version and English printout are (or can be) additional modules that can be ordered later.' },
  { key_name: 'invoicing_company', en: 'Intermediation, as well as invoicing, may take place from K-Soft Sverige AB, Box 2826, 187 28 Täby. In the future, we may choose to cooperate with another company for e.g. intermediation and invoicing. However, the customer relationship is with us.', sv: 'Intermediation, as well as invoicing, may take place from K-Soft Sverige AB, Box 2826, 187 28 Täby. In the future, we may choose to cooperate with another company for e.g. intermediation and invoicing. However, the customer relationship is with us.' },
  { key_name: 'payment_to_invoice_sender', en: 'The payment is made to the company from which the invoice comes.', sv: 'The payment is made to the company from which the invoice comes.' },
  { key_name: 'continuous_subscription', en: 'The annual fee is on a continuous basis, but if you do not wish to continue using the program, all you have to do is give notice thirty days before the start of the next one-year period.', sv: 'The annual fee is on a continuous basis, but if you do not wish to continue using the program, all you have to do is give notice thirty days before the start of the next one-year period.' },
  { key_name: 'introductory_offer', en: 'The introductory offer (SEK 99 per month) is for the annual fee Start for the first year.', sv: 'The introductory offer ( SEK 99 per month) is for the annual fee Start for the first year.' },
  { key_name: 'price_after_first_year', en: 'After the first year, the ordinary price is billed, which is currently, for annual fee Start, SEK 159 per month, for annual fee Remote control, SEK 300 per month and for annual fee Pro, SEK 333 per month.', sv: 'After the first year, the ordinary price is billed, which is currently, for annual fee Start, one hundred and fifty-nine kroner per month, for annual fee Remote control, three hundred kroner per month and for annual fee Pro, three hundred and thirty-three kroner per month.' },
  { key_name: 'default_after_year', en: 'After one year, the annual Remote Control fee is invoiced as standard, but you can choose Start or Pro by giving notice at any time before the due date.', sv: 'After one year, the annual Remote Control fee is invoiced as standard, but you can choose Start or Pro by giving notice at any time before the due date.' },
  { key_name: 'payment_acceptance', en: 'If you choose to keep the program by not notifying us by email within 14 days of registration that you do not wish to continue with the program, you accept that you will pay the invoice for your order.', sv: 'If you choose to keep the program by not notifying us by email within 14 days of registration that you do not wish to continue with the program, you accept that you will pay the invoice for your order.' },
  { key_name: 'no_cancel_late_payment', en: 'Failure to pay the invoice or late payment does not give the right to cancel the order.', sv: 'Failure to pay the invoice or late payment does not give the right to cancel the order.' },
  { key_name: 'logo_help', en: 'We are happy to help you with logo at a cost price.', sv: 'We are happy to help you with logo at a cost price.' },
  { key_name: 'license_legal', en: 'License for the use of 123 Fakturera is of course sold in accordance with applicable laws.', sv: 'License for the use of 123 Fakturera is of course sold in accordance with applicable laws.' },
  { key_name: 'data_storage_reason', en: 'In order to be able to help you more easily and provide you with support, as well as to comply with the laws, we, for natural reasons, have to store your information.', sv: 'In order to be able to help you more easily and provide you with support, as well as to comply with the laws, we, for natural reasons, have to store your information.' },
  { key_name: 'private_person_cancellation', en: 'If you order as a private person, you have the right to cancel as stated by law.', sv: 'If you order as a private person, you have the right to cancel as stated by law.' },
  { key_name: 'data_usage', en: 'Your information is stored so that we can help you, etc. We will use it to be able to help you if you need help, follow the laws regarding bookkeeping, etc.', sv: 'Your information is stored so that we can help you, etc. We will use it to be able to help you if you need help, follow the laws regarding bookkeeping, etc.' },
  { key_name: 'marketing_permission', en: 'When there are upgrades and the like, we may send you offers and the like about our products and services by email or the like. You may be contacted by email, post and telephone.', sv: 'When there are upgrades and the like, we may send you offers and the like about our products and services by email or the like. You may be contacted by email, post and telephone.' },
  { key_name: 'opt_out_marketing', en: 'If you don\'t want to be contacted, just send us an email about it.', sv: 'If you don\'t want to be contacted, just send us an email about it.' },
  { key_name: 'unsubscribe_upgrades', en: 'You can at any time ask not to be sent information about upgrades by email, letter or the like, and we will of course not do that.', sv: 'You can at any time ask not to be sent information about upgrades by email, letter or the like, and we will of course not do that.' },
  { key_name: 'data_processing_permission', en: 'For natural reasons, we have to store, process and move your data. Your information is stored until further notice.', sv: 'For natural reasons, we have to store, process and move your data. Your information is stored until further notice.' },
  { key_name: 'broad_data_permission', en: 'You give us permission to store, process and move your data, as well as to send you offers and the like by email, letter and the like, and tell others that you are customer. Due to the way it works with software, permission also needs to be given to other parties (current and future companies and persons related to the software, source code, website, etc.).', sv: 'You give us permission to store, process and move your data, as well as to send you offers and the like by email, letter and the like, and tell others that you are customer. Due to the way it works with software, permission also needs to be given to other parties...' },
  { key_name: 'gdpr_rights', en: 'You of course have the right to request access to, change and deletion of the information we hold about you. You also have the right to request restriction of data processing, and to object to data processing and the right to data portability. You have the right to complain to the supervisory authority.', sv: 'You of course have the right to request access to, change and deletion of the information we hold about you. You also have the right to request restriction of data processing, and to object to data processing and the right to data portability. You have the right to complain to the supervisory authority.' },
  { key_name: 'governing_law', en: 'The laws of Ireland are the applicable laws.', sv: 'The laws of Ireland are the applicable laws.' },
  { key_name: 'voluntary_order', en: 'Placing an order is of course completely voluntary.', sv: 'Placing an order is of course completely voluntary.' },
  { key_name: 'no_profiling', en: 'Of course, we do not use any automated profiling or decisions.', sv: 'Of course, we do not use any automated profiling or decisions.' },
  { key_name: 'contact_info', en: 'If you wish to contact us, please use the information on this website.', sv: 'If you wish to contact us, please use the information on this website.' },
  { key_name: 'registration_timestamp', en: 'Date and time of admission are entered automatically in our registers.', sv: '(Date and time of admission are entered automatically in our registers.)' },
  { key_name: 'closing_message', en: 'Our experience is that our customers are very satisfied with the way we work and hope and believe that this will also be your experience. Have a great day!', sv: 'Our experience is that our customers are very satisfied with the way we work and hope and believe that this will also be your experience. Have a great day!' }
]

module.exports = language_data
