const language_data = [
  { key_name: 'login_page', en: 'Log in', sv: 'Logga in' },
  { key_name: 'email_placeholder', en: 'Email address', sv: 'E-postadress' },
  { key_name: 'password_placeholder', en: 'Password', sv: 'Lösenord' },
  { key_name: 'login_button', en: 'Log in', sv: 'Logga in' },
  { key_name: 'register_link', en: 'Register', sv: 'Registrera' },
  { key_name: 'forgotten_password_link', en: 'Forgotten password?', sv: 'Glömt lösenord?' },
  { key_name: 'menu_home', en: 'Home', sv: 'Hem' },
  { key_name: 'menu_order', en: 'Order', sv: 'Beställning' },
  { key_name: 'menu_our_customers', en: 'Our Customers', sv: 'Våra kunder' },
  { key_name: 'menu_about_us', en: 'About us', sv: 'Om oss' },
  { key_name: 'menu_contact_us', en: 'Contact Us', sv: 'Kontakta oss' },
  { key_name: 'language_label', en: 'English', sv: 'Svenska' },
  { key_name: 'footer_company_name', en: '123 Fakturera', sv: '123 Fakturera' },
  { key_name: 'footer_rights', en: 'All rights reserved.', sv: 'Alla rättigheter förbehållna.' },
  { key_name: 'app_title', en: 'John Andre', sv: 'John Andre' },
  { key_name: 'company_name', en: 'Storjord AS', sv: 'Storjord AS' },
  { key_name: 'menu_invoices', en: 'Invoices', sv: 'Fakturor' },
  { key_name: 'menu_customers', en: 'Customers', sv: 'Kunder' },
  { key_name: 'menu_my_business', en: 'My Business', sv: 'Mitt företag' },
  { key_name: 'menu_invoice_journal', en: 'Invoice journal', sv: 'Fakturajournal' },
  { key_name: 'menu_price_list', en: 'Price List', sv: 'Prislista' },
  { key_name: 'menu_multiple_invoicing', en: 'Multiple Invoicing', sv: 'Flera faktureringar' },
  { key_name: 'menu_unpaid_invoices', en: 'Unpaid Invoices', sv: 'Obetalda fakturor' },
  { key_name: 'menu_offer', en: 'Offer', sv: 'Erbjudande' },
  { key_name: 'menu_inventory_control', en: 'Inventory Control', sv: 'Lagerkontroll' },
  { key_name: 'menu_member_invoicing', en: 'Member Invoicing', sv: 'Medlemsfakturering' },
  { key_name: 'menu_import_export', en: 'Import/Export', sv: 'Importera/Exportera' },
  { key_name: 'menu_log_out', en: 'Log out', sv: 'Logga ut' },
  { key_name: 'search_article_no', en: 'Search Article No...', sv: 'Sök artikelnummer...' },
  { key_name: 'search_product', en: 'Search Product...', sv: 'Sök produkt...' },
  { key_name: 'button_new_product', en: 'New Product', sv: 'Ny produkt' },
  { key_name: 'button_print_list', en: 'Print List', sv: 'Skriv ut lista' },
  { key_name: 'button_advanced_mode', en: 'Advanced mode', sv: 'Avancerat läge' },
  { key_name: 'table_header_article_no', en: 'Article No.', sv: 'Artikelnummer.' },
  { key_name: 'table_header_product_service', en: 'Product/Service', sv: 'Produkt/Tjänst' },
  { key_name: 'table_header_in_price', en: 'In Price', sv: 'Inköpspris' },
  { key_name: 'table_header_price', en: 'Price', sv: 'Pris' },
  { key_name: 'table_header_unit', en: 'Unit', sv: 'Enhet' },
  { key_name: 'table_header_in_stock', en: 'In Stock', sv: 'I lager' },
  { key_name: 'table_header_description', en: 'Description', sv: 'Beskrivning' }
]

module.exports = language_data
