
const userData = [
    {
    business_name: "Sajith Ram",
    contact_person: "John Doe",
    address: "12 Street Road",
    postal_number: "564321",
    city: "Chennai",
    email: "sajith@gmail.com",
    phone: "9876543210",
    password: 123456
  },
  {
    business_name: "Alpha Foods",
    contact_person: "John Doe",
    address: "12 Street Road",
    postal_number: "564321",
    city: "Chennai",
    email: "alpha@gmail.com",
    phone: "9876543210",
    password: 123456
  },
  {
    business_name: "Beta Traders",
    contact_person: "Michael",
    address: "45 Market Lane",
    postal_number: "420011",
    city: "Hyderabad",
    email: "beta@gmail.com",
    phone: "9988776655",
    password: 123456
  },
  {
    business_name: "Omega Distributors",
    contact_person: "Priya",
    address: "88 Highway Road",
    postal_number: "660223",
    city: "Bangalore",
    email: "omega@gmail.com",
    phone: "8877665544",
    password: 123456
  },
  {
    business_name: "Crystal Pvt Ltd",
    contact_person: "Rahul",
    address: "7 Tech Park",
    postal_number: "900221",
    city: "Mumbai",
    email: "crystal@gmail.com",
    phone: "7766554433",
    password: 123456
  },
  {
    business_name: "Glory Retail",
    contact_person: "Ananya",
    address: "22 Beach Side",
    postal_number: "301122",
    city: "Goa",
    email: "glory@gmail.com",
    phone: "6655443322",
    password: 123456
  }
]
const products = [
  { title: 'Rice 1kg', in_price: 45, price: 55, unit: 'kg', in_stock: 120, description: 'Premium white rice' },
  { title: 'Wheat Flour 1kg', in_price: 38, price: 48, unit: 'kg', in_stock: 90, description: 'Fresh wheat flour' },
  { title: 'Sugar 1kg', in_price: 40, price: 50, unit: 'kg', in_stock: 150, description: 'Fine grain sugar' },
  { title: 'Salt 1kg', in_price: 15, price: 20, unit: 'kg', in_stock: 200, description: 'Iodized salt' },
  { title: 'Toor Dal 1kg', in_price: 95, price: 120, unit: 'kg', in_stock: 60, description: 'Premium toor dal' },
  { title: 'Urad Dal 1kg', in_price: 70, price: 90, unit: 'kg', in_stock: 80, description: 'Black gram' },
  { title: 'Moong Dal 1kg', in_price: 85, price: 110, unit: 'kg', in_stock: 70, description: 'Yellow moong dal' },
  { title: 'Chana Dal 1kg', in_price: 60, price: 75, unit: 'kg', in_stock: 85, description: 'Split chickpeas' },
  { title: 'Groundnut Oil 1L', in_price: 130, price: 150, unit: 'L', in_stock: 90, description: 'Filtered groundnut oil' },
  { title: 'Sunflower Oil 1L', in_price: 115, price: 135, unit: 'L', in_stock: 110, description: 'Refined sunflower oil' },
  { title: 'Coconut Oil 1L', in_price: 160, price: 185, unit: 'L', in_stock: 40, description: 'Pure coconut oil' },
  { title: 'Tea Powder 250g', in_price: 70, price: 90, unit: 'g', in_stock: 60, description: 'Strong tea powder' },
  { title: 'Coffee Powder 200g', in_price: 130, price: 155, unit: 'g', in_stock: 50, description: 'Filter coffee mix' },
  { title: 'Milk 1L', in_price: 40, price: 48, unit: 'L', in_stock: 200, description: 'Fresh milk pack' },
  { title: 'Curd 500g', in_price: 25, price: 32, unit: 'g', in_stock: 150, description: 'Thick curd pack' },
  { title: 'Bread 400g', in_price: 32, price: 40, unit: 'g', in_stock: 80, description: 'White bread loaf' },
  { title: 'Eggs (6 pack)', in_price: 35, price: 45, unit: 'pack', in_stock: 70, description: 'Fresh eggs' },
  { title: 'Basmati Rice 1kg', in_price: 110, price: 140, unit: 'kg', in_stock: 50, description: 'Long grain basmati' },
  { title: 'Poha 1kg', in_price: 40, price: 52, unit: 'kg', in_stock: 65, description: 'Flattened rice' },
  { title: 'Ragi Flour 1kg', in_price: 55, price: 70, unit: 'kg', in_stock: 55, description: 'Finger millet flour' },
  { title: 'Besan 1kg', in_price: 65, price: 80, unit: 'kg', in_stock: 75, description: 'Gram flour' },
  { title: 'Maida 1kg', in_price: 32, price: 45, unit: 'kg', in_stock: 95, description: 'Refined flour' },
  { title: 'Vermicelli 500g', in_price: 30, price: 38, unit: 'g', in_stock: 85, description: 'Roasted vermicelli' },
  { title: 'Pasta 500g', in_price: 45, price: 60, unit: 'g', in_stock: 60, description: 'Durum wheat pasta' },
  { title: 'Noodles Pack', in_price: 10, price: 15, unit: 'pack', in_stock: 150, description: 'Instant noodles' },
  { title: 'Soap Bar', in_price: 22, price: 30, unit: 'piece', in_stock: 120, description: 'Bathing soap' },
  { title: 'Shampoo 180ml', in_price: 85, price: 110, unit: 'ml', in_stock: 75, description: 'Anti-dandruff shampoo' },
  { title: 'Toothpaste 100g', in_price: 40, price: 55, unit: 'g', in_stock: 70, description: 'Fluoride toothpaste' },
  { title: 'Toothbrush', in_price: 18, price: 25, unit: 'piece', in_stock: 100, description: 'Soft bristles' },
  { title: 'Detergent Powder 1kg', in_price: 65, price: 80, unit: 'kg', in_stock: 95, description: 'Washing powder' },
  { title: 'Detergent Bar', in_price: 10, price: 15, unit: 'piece', in_stock: 120, description: 'Cloth washing bar' },
  { title: 'Dishwash Liquid 500ml', in_price: 40, price: 55, unit: 'ml', in_stock: 60, description: 'Lemon fragrance' },
  { title: 'Bath Towel', in_price: 120, price: 150, unit: 'piece', in_stock: 40, description: 'Cotton towel' },
  { title: 'Face Towel', in_price: 25, price: 35, unit: 'piece', in_stock: 60, description: 'Soft cotton towel' },
  { title: 'Green Gram 1kg', in_price: 95, price: 120, unit: 'kg', in_stock: 55, description: 'Whole green gram' },
  { title: 'Black Pepper 100g', in_price: 60, price: 75, unit: 'g', in_stock: 35, description: 'Whole pepper' },
  { title: 'Cumin 100g', in_price: 45, price: 60, unit: 'g', in_stock: 40, description: 'Whole jeera' },
  { title: 'Turmeric Powder 200g', in_price: 28, price: 38, unit: 'g', in_stock: 50, description: 'Pure turmeric' },
  { title: 'Chilli Powder 200g', in_price: 45, price: 60, unit: 'g', in_stock: 45, description: 'Red chilli powder' },
  { title: 'Coriander Powder 200g', in_price: 30, price: 40, unit: 'g', in_stock: 45, description: 'Ground coriander' },
  { title: 'Garam Masala 100g', in_price: 55, price: 70, unit: 'g', in_stock: 30, description: 'Mixed spices' },
  { title: 'Honey 250g', in_price: 95, price: 120, unit: 'g', in_stock: 25, description: 'Pure honey' },
  { title: 'Jam 500g', in_price: 80, price: 100, unit: 'g', in_stock: 35, description: 'Mixed fruit jam' },
  { title: 'Butter 100g', in_price: 45, price: 55, unit: 'g', in_stock: 40, description: 'Salted butter' },
  { title: 'Ghee 500ml', in_price: 210, price: 250, unit: 'ml', in_stock: 25, description: 'Pure ghee' },
  { title: 'Biscuits Pack', in_price: 20, price: 30, unit: 'pack', in_stock: 130, description: 'Tea biscuits' },
  { title: 'Chips Pack', in_price: 10, price: 15, unit: 'pack', in_stock: 150, description: 'Potato chips' },
  { title: 'Juice 1L', in_price: 75, price: 95, unit: 'L', in_stock: 45, description: 'Fruit juice' },
  { title: 'Soda Bottle', in_price: 20, price: 30, unit: 'bottle', in_stock: 80, description: 'Aerated drink' },
  { title: 'Cornflakes 500g', in_price: 110, price: 130, unit: 'g', in_stock: 30, description: 'Breakfast cereal' },
  { title: 'Oats 1kg', in_price: 90, price: 110, unit: 'kg', in_stock: 40, description: 'Roll'}
]

module.exports = { userData, products}